sudo: required
language: python
services:
- docker
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- cd pointdistribution
- python manage.py test
- cd ..
after_success:
- test $TRAVIS_BRANCH == "master" && docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  $DOCKER_URL & docker build -t $DOCKER_URL/100point:$APP_MAJOR_VERSION.$APP_MINOR_VERSION.$TRAVIS_BUILD_NUMBER
  . && docker push $DOCKER_URL/100point:$APP_MAJOR_VERSION.$APP_MINOR_VERSION.$TRAVIS_BUILD_NUMBER
env:
  global:
  - secure: ebgkNv+blMg4/CQime2p9NtNaN476EoZmx4ahe6lv1DLXDABw2zUgaRLpDIUGTokI267BskkUzBlqDpY655Ei5L4egpxVNdpkhLra1qPg3cA/aaaf1gLry90oVdzuiJkkQBvFXUX4VJyUzTRPy3vdwEuvQXEjT+9IsRM4L+Ymqqg03nm4LWDrjet89S4DT5WnKwksy7yK5y3qYRHBjaU8qpE1hgA45nziPZSo5+XGX24TrLqDyLwqJD0TUlGGEK/kkifE3Z/zokvgIeQ670PTQ/fm13lWIU8gGzWwmKNZ/hsevs52vgAD976dSsDpBPmD7rNm3II4Bugs1VWd6dlZwRjnvwqQIqAhNGPCXQqq0C1Mipebc5lpa/HLZlZyrSctPJ3GRj0+I1uoRIwwA5YfFH+Tj7cEU7ZPQ/+0vZV3RT3zJG06eLQJdp2HbYVS8DZqD3PT7bxw2Qcec7BIUfwNirg6bgI8iEfSmRVTiDgb0LECsf3HtXdlwAEjocKVRvTl/bznV6YdRUIAS1YxyCAGMm6mBvImHeOYlLLrlH2DBl+ikynNvWr7hP1Ms8/PvVBuRk/e5ivtsgYe/lT/0a8rYLHY9W1ypKBSxbjFDqeYLiplJ+uy0iPTD1s+84F/Q5ZxVrzS90beKNVsROoEx1PliJMJRuduf11b7O83TouOLU=
  - secure: E9FghnG0/Gs3RpBezcRzKWBaEm6CpGNcAeu2PC2QDQ6QlRPd8mCI6SkQrZDNj28fv865WnR+LDdJq84aF3UxYNLlyuVj36JOXjEa6f+Paiu157DWUchQl/SRIjXXjkHdpA8fhbMu7Kp8KEjjSzcmg9BOeaW2UdrxZPQczkntrKdZ1edrZHSlE3sj6rm/du4Gs+2G19Ifg8E4qzVxq2iXsQzSVkCj+61+mUgLL2Skbcij8SGqZf4nFduJlQvIGVltFnCjbOCWMoa9TIMkeb4rsWcuJk+VLHN9T+0k4TIqIHXRxfFdrdLweYy+4TJcMXyNT1mtywxXwFwqDyB1cuSwClN6Or3thxBKz1lOmJXQYPhnNbYwQ9hMZ7/b+M1XMcNjyVr3WKHe+oOAds2RaKQmlmdM3l8f7NFm3AxlILSuXTMNMFA1oUFUa8tfKGcSSdA/l+m8MxQZU25GdUrLnFcM7K49FtNWBdFv6putNpWxGqY8EdYP1mkyX//drCzZ7jzuDJvhvCwZGPdc1kTQRFdJRhF9/6qx2Uv7T71xN3o2AmjzaP0fuzhW76UHWftOv1KoMJshQjC+DAKlLGLldDvAoq3LSN7AFqt3en31Vf/hVMoQbf152VnBPsHlabijF58aBJFL3zDPlYQwyVbLy3ULKuzelFw8+Jxfdg6h+rsJsVc=
  - secure: KSdbCefYsx1rRi1qtbqh0STP7vYDxRlY2QmqGUTd/UHMnQfeLEictgN9HI2YULXieo0dn2BIML4ZGLI/ILWuIa0+FaP7WcNEoX4kxjF+gMVV6XiaC/rQ8LopBgslyCwkSTmLVABpfdNcpOZV71l7PHWqewyVqHMbgLLvC+ENqO44aBEes0Gli2agEnynB7K/PQi2HA+mmA0IiWVOy/NHIzjw6x2s/rRAkY4Qz1e3pwoOLHQeKb152u6R835nvM5uZQ/eYGlmuhsQLYya66B2CzMuXajA0B7sDcpZez5wOJLAbTbTC8YmR1p6fmPvmNa9uQ4wkTNAkBDj/Qd0Pz0oxEAzxf+JpSNQqDp8/t+c12eGc6IvC4WHKOOWGWht5EzYoyLhRHNzIcM/i0LmiN5K4zXE4mq7uwU6Yl7BECazb6o1HXt7wIHCpGG2k/9FFWSKM244dqrxWbha2ZvEjugWzmdzv1STUYpuJy97uDLSXx4d8WEGfuiKEa6bP6lDJwjCTe7FK7SduRPHGebccEhtlOztRAvhy9kiXwIFvN/Gmgw18TM1D2aCPuDZvBx9IA2BpINe7q/XN8T1Bwqhmj5D25HIUs2vCxZmT/V+zMLhs1QH/3F+hGOhPvERz2xxN/tpA5PtomFM0cjon+hSkL5gtb2KomFaIFc2kIRPoc50oUY=
