language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
- cd pointdistribution
- python manage.py test
- cd ..
after_success:
- test $TRAVIS_BRANCH == "master" && docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  $DOCKER_URL & docker build -t $DOCKER_URL/100point:$APP_MAJOR_VERSION.$APP_MINOR_VERSION.$TRAVIS_BUILD_NUMBER
  . && docker push $DOCKER_URL/100point:$APP_MAJOR_VERSION.$APP_MINOR_VERSION.$TRAVIS_BUILD_NUMBER
