language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - cd pointdistribution
  - python manage.py test
deploy:
  provider: azure_web_apps
  username: "deployment-100"
  password: "100-points"
  site: "100-point-discovery-backend"